export const CHECK_SESSION = 'checkSession'
export const LOGIN = 'login'
export const GET_BOARDS = 'getBoards'
export const GET_PINS = 'getPins'
export const SELECT_INTERVAL = 'selectInterval'
export const SELECT_BOARD = 'selectBoard'
export const NEXT_IMAGE = 'nextImage'
export const ON_IMAGE_CLICK = 'onImageClick'
